<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP" failures="2" tests="14" name="factorial_site_testing.FactorialDataProviderTest" time="11.863" errors="0" timestamp="2025-07-12T13:39:09 IST" skipped="0">
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.832"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.788"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.812">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at factorial_site_testing.FactorialDataProviderTest.verifyFactorial(FactorialDataProviderTest.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- verifyFactorial -->
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.921"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.881">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at factorial_site_testing.FactorialDataProviderTest.verifyFactorial(FactorialDataProviderTest.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- verifyFactorial -->
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.882"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.847"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.935"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.786"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.783"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.845"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.814"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.839"/>
  <testcase classname="factorial_site_testing.FactorialDataProviderTest" name="verifyFactorial" time="0.898"/>
</testsuite> <!-- factorial_site_testing.FactorialDataProviderTest -->
